- hosts: web 
  become: yes
  tasks:
    - name: display hostname
      command: hostname
                                  
    - name: display date
      command: date
                                                  
   
                                                                
